FROM python:3.11-slim-bookworm

COPY --from=builder /opt/spark /opt/spark

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    openjdk-17-jre-headless \
    procps \
    python-is-python3 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    pyarrow==21.0 \
    pyspark==4.0 \
    minio==7.2 \
    python-dotenv==1.1 \
    pandas==2.3 \
    tqdm==4.67 \
    jupyterlab==4.4.5

ENV SPARK_HOME="/opt/spark"
ENV PATH="${SPARK_HOME}/bin:${SPARK_HOME}/sbin:${PATH}"
ENV PYTHONPATH="${SPARK_HOME}/python:${SPARK_HOME}/python/lib/py4j-0.10.9.7-src.zip:${PYTHONPATH}"

RUN groupadd --system --gid 1000 spark && \
    useradd --system --create-home --uid 1000 --gid spark sparkuser && \
    chown -R sparkuser:spark "${SPARK_HOME}"

USER sparkuser

WORKDIR /home/sparkuser/notebooks

ENTRYPOINT ["bash", "-c", "jupyter lab --ip='0.0.0.0' --port=8888 --NotebookApp.token=''"]