FROM python:3.11-slim-bookworm AS builder

ARG AWS_SDK_VERSION=1.12.262
ARG HADOOP_VERSION=3.4.1
ARG SPARK_VERSION=3.5.6

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    curl \
    openjdk-17-jre-headless \
    && rm -rf /var/lib/apt/lists/*

ENV SPARK_HOME="/opt/spark"
ENV SPARK_TGZ_URL="https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop3.tgz"

RUN mkdir -p /opt/spark && \
    curl -sSL ${SPARK_TGZ_URL} -o /tmp/spark.tgz && \
    tar -xzf /tmp/spark.tgz -C ${SPARK_HOME} --strip-components=1 && \
    rm /tmp/spark.tgz

ENV AWS_JAVA_SDK_BUNDLE_JAR_URL="https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_SDK_VERSION}/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar"
ENV HADOOP_AWS_JAR_URL="https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_VERSION}/hadoop-aws-${HADOOP_VERSION}.jar"

RUN curl -sSL "${HADOOP_AWS_JAR_URL}" -o "${SPARK_HOME}/jars/hadoop-aws-${HADOOP_VERSION}.jar" && \
    curl -sSL "${AWS_JAVA_SDK_BUNDLE_JAR_URL}" -o "${SPARK_HOME}/jars/aws-java-sdk-bundle-${AWS_SDK_VERSION}.jar"

RUN groupadd --system --gid 1000 spark && \
    useradd --system --uid 1000 --gid spark sparkuser && \
    chown -R sparkuser:spark "${SPARK_HOME}"

WORKDIR "${SPARK_HOME}"